const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

async function main() {
  const products = [
    {
      name: 'Classic Leather Jacket',
      description: 'A timeless leather jacket with a tailored fit and premium finish.',
      price: 179.99,
      stock: 14,
      category: 'Apparel',
      images: ['https://example.com/images/leather-jacket-1.jpg'],
      sold: 52,
    },
    {
      name: 'Eco-Friendly Water Bottle',
      description: 'Reusable stainless steel bottle with leak-proof cap and modern design.',
      price: 24.5,
      stock: 72,
      category: 'Home',
      images: ['https://example.com/images/water-bottle-1.jpg'],
      sold: 121,
    },
    {
      name: 'Wireless Earbuds Pro',
      description: 'Noise-cancelling wireless earbuds with long battery life and fast charging.',
      price: 129.99,
      stock: 32,
      category: 'Electronics',
      images: ['https://example.com/images/earbuds-pro-1.jpg'],
      sold: 143,
    },
    {
      name: 'Bamboo Cutting Board Set',
      description: 'Durable bamboo board set with juice groove and non-slip edges.',
      price: 34.95,
      stock: 45,
      category: 'Kitchen',
      images: ['https://example.com/images/cutting-board-set-1.jpg'],
      sold: 64,
    },
    {
      name: 'Urban Running Sneakers',
      description: 'Lightweight running shoes with breathable mesh and responsive cushioning.',
      price: 89.0,
      stock: 26,
      category: 'Footwear',
      images: ['https://example.com/images/running-sneakers-1.jpg'],
      sold: 91,
    },
    {
      name: 'Minimalist Desk Lamp',
      description: 'LED desk lamp with touch controls and adjustable brightness levels.',
      price: 42.9,
      stock: 58,
      category: 'Home',
      images: ['https://example.com/images/desk-lamp-1.jpg'],
      sold: 37,
    },
    {
      name: 'Smart Fitness Watch',
      description: 'Fitness tracker with heart rate monitor, GPS, and sleep tracking.',
      price: 159.99,
      stock: 18,
      category: 'Electronics',
      images: ['https://example.com/images/fitness-watch-1.jpg'],
      sold: 203,
    },
    {
      name: 'Organic Cotton T-Shirt',
      description: 'Soft organic cotton tee in multiple colors with everyday comfort.',
      price: 27.0,
      stock: 120,
      category: 'Apparel',
      images: ['https://example.com/images/cotton-tshirt-1.jpg'],
      sold: 86,
    },
    {
      name: 'Premium Yoga Mat',
      description: 'Non-slip yoga mat with extra cushioning for home workouts.',
      price: 49.5,
      stock: 34,
      category: 'Fitness',
      images: ['https://example.com/images/yoga-mat-1.jpg'],
      sold: 52,
    },
    {
      name: 'Retro Gaming Console',
      description: 'Compact retro gaming console preloaded with classic titles.',
      price: 69.99,
      stock: 22,
      category: 'Electronics',
      images: ['https://example.com/images/retro-console-1.jpg'],
      sold: 44,
    },
    {
      name: 'Designer Sunglasses',
      description: 'UV-protective sunglasses with modern frame and premium lenses.',
      price: 79.99,
      stock: 39,
      category: 'Accessories',
      images: ['https://example.com/images/sunglasses-1.jpg'],
      sold: 108,
    },
    {
      name: 'Travel Backpack',
      description: 'Durable travel backpack with multiple compartments and water-resistant fabric.',
      price: 74.0,
      stock: 51,
      category: 'Travel',
      images: ['https://example.com/images/travel-backpack-1.jpg'],
      sold: 61,
    },
    {
      name: 'Deluxe Coffee Maker',
      description: 'Automatic coffee maker with programmable timer and brew strength control.',
      price: 119.0,
      stock: 17,
      category: 'Kitchen',
      images: ['https://example.com/images/coffee-maker-1.jpg'],
      sold: 78,
    },
    {
      name: 'Gaming Chair',
      description: 'Ergonomic gaming chair with lumbar support and recline function.',
      price: 199.99,
      stock: 12,
      category: 'Furniture',
      images: ['https://example.com/images/gaming-chair-1.jpg'],
      sold: 31,
    },
    {
      name: 'Smart Home Speaker',
      description: 'Voice-controlled smart speaker with rich audio and home automation support.',
      price: 99.99,
      stock: 29,
      category: 'Electronics',
      images: ['https://example.com/images/smart-speaker-1.jpg'],
      sold: 140,
    },
    {
      name: 'Luxury Bed Sheets',
      description: 'Breathable high-thread-count sheets for a comfortable night’s sleep.',
      price: 89.99,
      stock: 23,
      category: 'Home',
      images: ['https://example.com/images/bed-sheets-1.jpg'],
      sold: 49,
    },
    {
      name: 'Portable Bluetooth Speaker',
      description: 'Compact speaker with deep bass and up to 12 hours of playback.',
      price: 54.9,
      stock: 48,
      category: 'Electronics',
      images: ['https://example.com/images/bluetooth-speaker-1.jpg'],
      sold: 98,
    },
    {
      name: 'Stainless Steel Cookware Set',
      description: '10-piece cookware set with non-stick interior and tempered glass lids.',
      price: 179.0,
      stock: 16,
      category: 'Kitchen',
      images: ['https://example.com/images/cookware-set-1.jpg'],
      sold: 29,
    },
    {
      name: 'Children’s Storybook Collection',
      description: 'Set of 8 illustrated storybooks for early readers.',
      price: 39.99,
      stock: 64,
      category: 'Books',
      images: ['https://example.com/images/storybook-collection-1.jpg'],
      sold: 85,
    },
    {
      name: 'Mountain Bike Helmet',
      description: 'Lightweight helmet with adjustable straps and ventilation.',
      price: 59.0,
      stock: 34,
      category: 'Sports',
      images: ['https://example.com/images/bike-helmet-1.jpg'],
      sold: 67,
    },
    {
      name: 'Bluetooth Sleep Mask',
      description: 'Soft travel sleep mask with built-in Bluetooth audio.',
      price: 32.5,
      stock: 27,
      category: 'Travel',
      images: ['https://example.com/images/sleep-mask-1.jpg'],
      sold: 39,
    },
    {
      name: 'Stylish Leather Wallet',
      description: 'Slim leather wallet with RFID protection and multiple card slots.',
      price: 49.99,
      stock: 43,
      category: 'Accessories',
      images: ['https://example.com/images/leather-wallet-1.jpg'],
      sold: 72,
    },
    {
      name: 'Mini Projector',
      description: 'Portable projector for movies, presentations, and gaming on the go.',
      price: 145.0,
      stock: 19,
      category: 'Electronics',
      images: ['https://example.com/images/mini-projector-1.jpg'],
      sold: 56,
    },
    {
      name: 'Comfort Sneakers',
      description: 'Breathable everyday sneakers with memory foam insoles.',
      price: 69.99,
      stock: 38,
      category: 'Footwear',
      images: ['https://example.com/images/comfort-sneakers-1.jpg'],
      sold: 103,
    },
    {
      name: 'Classic Denim Jacket',
      description: 'Everyday denim jacket with a relaxed fit and durable stitching.',
      price: 84.0,
      stock: 31,
      category: 'Apparel',
      images: ['https://example.com/images/denim-jacket-1.jpg'],
      sold: 60,
    },
    {
      name: 'Aromatherapy Candle Set',
      description: 'Set of scented candles for relaxation and home ambiance.',
      price: 29.99,
      stock: 55,
      category: 'Home',
      images: ['https://example.com/images/candle-set-1.jpg'],
      sold: 38,
    },
    {
      name: 'Digital Art Tablet',
      description: 'Drawing tablet with responsive pen and multi-touch controls.',
      price: 159.99,
      stock: 15,
      category: 'Electronics',
      images: ['https://example.com/images/art-tablet-1.jpg'],
      sold: 24,
    },
    {
      name: 'Premium Knife Set',
      description: 'Professional kitchen knife set with wooden block and stainless blades.',
      price: 129.99,
      stock: 21,
      category: 'Kitchen',
      images: ['https://example.com/images/knife-set-1.jpg'],
      sold: 42,
    },
    {
      name: 'Travel Organizer Kit',
      description: 'Organizer kit for cables, chargers, and travel essentials.',
      price: 27.5,
      stock: 44,
      category: 'Travel',
      images: ['https://example.com/images/travel-organizer-1.jpg'],
      sold: 50,
    },
    {
      name: 'Luxury Bath Towel Set',
      description: 'Ultra-soft towel set with high absorbency and elegant design.',
      price: 59.0,
      stock: 29,
      category: 'Home',
      images: ['https://example.com/images/towel-set-1.jpg'],
      sold: 33,
    }
  ]

  await prisma.product.deleteMany({})
  await prisma.product.createMany({ data: products })
  console.log(`${products.length} products seeded.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
